### ISSUE TITLE
Slow _sign in Crypt/Perl/ECDSA/PrivateKey.pm

### ISSUE THREAD

**Issue by moseleymark** [FGasper/p5-Crypt-Perl#12]
This isn't an issue, per se, but I'm hoping for a workaround.

I'm using your Net::ACME2 module for creating LetsEncrypt certs. I noticed that creating a cert (and I'm creating almost 2 million) takes quite a while (upwards of 20 seconds).

I traced down the elapsed time to calls to Crypt::Perl::ECDSA::PrivateKey::_sign, when Net::ACME2 calls sign_jwa to sign a JWT token before sending a request to LetsEncrypt. Each call takes about 5 seconds and for a full run (no pending challenges, etc), there's at least a handful of requests to LetsEncrypt's API. Through copious 'print STDERR', all of that time seems to be spent in Crypt::Perl::ECDSA::PrivateKey::_sign, when it calls:

my $Q = $G->multiply($k);

I can see from debugging (and from trying to wrap my head around Crypt::Perl::ECDSA::EC::Point) that it's doing math on enormous numbers, all in pure Perl. When I run simple tests, I can see the script driving a CPU core up to 100% (they're oldish CPUs, but usually are fairly capable), so it's clearly CPU-bound.

I'm hoping you might have a suggestion/workaround/etc for some way to speed this up. Is it possible to substitute in an XS module for the JWT signing (albeit conditionally, so that the pure Perl way still works)? Or potentially some setting (in Net::ACME2 or elsewhere) that I'm missing?

Thanks!

**Comment by FGasper** [comment]
@moseleymark Did you try installing Math::BigInt::GMP? Crypt::Perl (Net::ACME2’s crypto backend) should pull that in if it’s present, and it will dramatically speed up ECDSA calculations. You can also try Math::BigInt::Pari, but the speed bump doesn’t seem as dramatic there.

I do have a branch that abstracts out the crypto logic to use CryptX if it’s present, but I’m not sure there’s a significant advantage to that versus Math::BigInt::GMP, so I’ve not merged it.

**Comment by moseleymark** [comment]
You're awesome, that works perfectly!

That took the time for _sign() to run from 5 seconds to 0.5 seconds.

Now I just wish I'd asked 4 hours ago :)
