### ISSUE TITLE
Don't ignore SIGXCPU

### ISSUE THREAD

**Issue by eserte** [FGasper/p5-Crypt-Perl#16]
Please don't ignore SIGXCPU --- probably this is targetting against my smokers which run with a cpu limit of one hour. IMHO more than one hour runtime for a single test is too much and neither practicable for a smoker instance nor for a user installation.

**Comment by FGasper** [comment]
Noted. I'll fix. Thank you!

**Comment by FGasper** [comment]
> IMHO more than one hour runtime for a single test is too much and neither practicable for a smoker instance nor for a user installation.

I don’t see why or how this test takes >1hr on your smokers, esp. since you have Math::BigInt::GMP and the key size is only 512 bits. On my RPi 3 the test takes about 80 seconds.

It _may_ be the issue that Math::ProvablePrime fixed a bit ago, actually. I’ll bump the dependency and see.

**Comment by FGasper** [comment]
Fixed in latest dev build.
