### ISSUE TITLE
Tests look like they're stuck in a loop even when they're not

### ISSUE THREAD

**Issue by DrHyde** [FGasper/p5-Crypt-Perl#7]
The tests spew out screenfuls of this noise:

    read EC key
    writing EC key
    read EC key
    writing EC key
    read EC key
    writing EC key
    ...

which looks awfully like something is stuck in a loop. I think it would be more installer-friendly to just remain silent, and to perhaps spit out a note about "these tests can take a really long time, please be patient". Just spitting a message to STDERR at the start of a slow test file should be enough.

**Comment by FGasper** [comment]
Added in f1b0e85. Thanks!
